#!/usr/bin/bash

ROUTE_TODO_DB = "api/LiteDbTodoItems"

CERT_CONTOSO = "contoso.com.crt"
PEM_CONTOSO = "contoso.com.pem"

#ROUTE_DEVICE_DB = "api/LiteDbDeviceItems"
ROUTE_DEVICE_DB = "v1/devices/version_check"

#  test local

#BASE_URL_LOCAL = "http://10.1.26.50:5556/"

BASE_URL_LOCAL = "http://192.168.56.1:5556/"

API_TODO_LOCAL = BASE_URL_LOCAL + ROUTE_TODO_DB


API_DEVICE_LOCAL = BASE_URL_LOCAL + ROUTE_DEVICE_DB

#  test remote

BASE_URL_REMOTE = "http://123.51.217.96:5555/"

API_TODO_REMOTE = BASE_URL_REMOTE + ROUTE_TODO_DB

API_DEVICE_REMOTE = BASE_URL_REMOTE + ROUTE_DEVICE_DB


#  test contoso

BASE_URL_CONTOSO = "https://www.contoso.com/"

API_TODO_CONTOSO = BASE_URL_CONTOSO + ROUTE_TODO_DB

API_DEVICE_CONTOSO = BASE_URL_CONTOSO + ROUTE_DEVICE_DB

#  test primax

BASE_URL_PRIMAX = "http://pthqdkssw.primax.com.tw:5555/"

API_TODO_PRIMAX = BASE_URL_PRIMAX + ROUTE_TODO_DB

API_DEVICE_PRIMAX = BASE_URL_PRIMAX + ROUTE_DEVICE_DB


#  test primax ssl

BASE_URL_PRIMAX_SSL = "http://pthqdkssw.primax.com.tw:443/"

API_TODO_PRIMAX_SSL = BASE_URL_PRIMAX_SSL + ROUTE_TODO_DB

API_DEVICE_PRIMAX_SSL = BASE_URL_PRIMAX_SSL + ROUTE_DEVICE_DB
